### PR TITLE
update offending author key line below 64 characters

### PR DESCRIPTION
**Pull request by thedoubl3j**
### What does this PR do?
- fix galaxy.yml bug for author field

### What ticket does this PR close?
na

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

### CODE REVIEW

**Comment by izgeri** [comment]
hey @thedoubl3j - thanks for submitting this fix. can you please also [amend your commit to have the DCO signoff](https://github.com/cyberark/community/blob/master/CONTRIBUTING.md#signing-off-a-commit)?

it looks like the 2.10 sanity check failed with this update, too:
```
ERROR: Found 2 yamllint issue(s) which need to be resolved:
ERROR: galaxy.yml:7:7: error: syntax error: found character '@' that cannot start any token (syntax)
ERROR: galaxy.yml:7:7: unparsable-with-libyaml: while scanning for the next token - found character that cannot start any token
```

**Comment by rpothier** [comment]
Hi @thedoubl3j Did you [amend your commit to have the DCO signoff](https://github.com/cyberark/community/blob/master/CONTRIBUTING.md#signing-off-a-commit)? I don't see it.

**Comment by thedoubl3j** [comment]
signed off + rebased @rpothier

**Review by izgeri — APPROVED** [review]
LGTM

**Pull request merged**
