### PR TITLE
Add R&D Dev Team members to the authors list

### PR DESCRIPTION
**Pull request by orenbm**
Add the developers who wrote the original code to
the authors list

### CODE REVIEW

**Comment by orenbm** [comment]
No probs. care to take this with your team? i am not sure which teams you would like to tag in this repo. thanks :)

**Comment by uCatu** [comment]
> let's revise this to refer to teams or @cyberark/developers generally rather than listing specific people

I think `cyberark/developers` handler just got 56 developers to be subscribed/notified :(

**Comment by orenbm** [comment]
> > let's revise this to refer to teams or @cyberark/developers generally rather than listing specific people
> 
> I think `cyberark/developers` handler just got 56 developers to be subscribed/notified :(

yes, it better be a specific team but i am not quite sure who is responsible for this repo (community/bizdev)

**Comment by uCatu** [comment]
> > > let's revise this to refer to teams or @cyberark/developers generally rather than listing specific people
> > 
> > 
> > I think `cyberark/developers` handler just got 56 developers to be subscribed/notified :(
> 
> yes, it better be a specific team but i am not quite sure who is responsible for this repo (community/bizdev)

I mean, currently, on Github, for this thread... I got notified :)

**Comment by orenbm** [comment]
> > > > let's revise this to refer to teams or @cyberark/developers generally rather than listing specific people
> > > 
> > > 
> > > I think `cyberark/developers` handler just got 56 developers to be subscribed/notified :(
> > 
> > 
> > yes, it better be a specific team but i am not quite sure who is responsible for this repo (community/bizdev)
> 
> I mean, currently, on Github, for this thread... I got notified :)

yes, i understood that. this indicates that the same 56 developers will get notified if someone wants to contact the developers of this repo and we don't want that. we want the maintainers of this repo to be notified.

**Comment by izgeri** [comment]
you can tag @cyberark-bizdev and @cyberark/community-and-integrations-team as the owners.

did this keep notifying everyone every time you quoted `@cyberark/developers` above? 😂

**Comment by garymoon** [comment]
Un 👏 sub 👏 scribe.

**Comment by orenbm** [comment]
@cyberark/community-and-integrations-team ready for review

**Pull request merged**
