### PR TITLE
Update role path in the README example

### PR DESCRIPTION
**Pull request by raghav1674**
### Desired Outcome

Updated role path from conjur-host-identity -> conjur_host_identity in README.md

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?
    Updated README.md role path 
- _How should the reviewer approach this PR, especially if manual tests are required?
    N.A.
- _Are there relevant screenshots you can add to the PR description?
   N.A.

### Connected Issue/Story

N.A.

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [X] The changes in this PR do not require tests

#### Documentation

- [X] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [X] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [X] There are no security aspects to these changes

### CODE REVIEW

**Comment by Vignesh-Seethapathy** [comment]
Merge this PR ASAP. The mistake in the README.md is cascading to all the other documentations in the web. Although the mistake is simple it took me  quite a bit of time to figure out why ansible was not able to find the role.

**Comment by john-odonnell** [comment]
Thanks for the contribution, @raghav1674 - sorry for the wait. Could you rebase your PR with the most recent content from `main`?

**Comment by raghav1674** [comment]
sure @john-odonnell , Sorry for the delay. I will rebase with main.

**Review by john-odonnell — APPROVED** [review]
LGTM - thanks, @raghav1674!

**Pull request merged**
