### PR TITLE
Fix tests on docker-compose v2

### PR DESCRIPTION
**Pull request by szh**
### Desired Outcome

Tests should pass both with docker-compose v1 (as on Jenkins) and v2 (as on local machines).

Docker Compose v2 changes the default naming convention for containers, from '_' to '-'. To support both v1 and v2, explicitly set the container_name in docker-compose.yml for the conjur_variable tests.
For the roles/conjur_host_identity tests we can't use container_name because we use scaling, and docker-compose doesn't support specifying a container_name when requiring multiple instances of a container. Instead we use different inventory.j2 template files for the different docker-compose versions.

### Implemented Changes

- Conjur_variable tests: Updated docker-compose.yml to explicitly set container_name
- Conjur_variable tests: Updated tests to use the new container name
- Roles/conjur_host_identity tests: Use separate inventory.j2 files for different docker-compose versions

### Connected Issue/Story

N/A

### Definition of Done

- [x] Tests pass on docker-compose v2 locally
- [x] Tests pass on docker-compose v1 on Jenkins

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

### CODE REVIEW

**Comment by john-odonnell** [comment]
I was going to note that we should also extend this fix to the tests in `roles/conjur_host_identity/tests/`, but I don't think we can apply this same strategy.

The tests there have the same problem when building Ansible's inventory with `inventory.j2` - the separators around `test_app_x` change with docker-compose version:
```
testapp]
{{ lookup('env','COMPOSE_PROJECT_NAME') }}_test_app_ubuntu_[1:2] ansible_connection=docker
{{ lookup('env','COMPOSE_PROJECT_NAME') }}_test_app_centos_[1:2] ansible_connection=docker
```

Problem is, if we use `container_name` in the compose file, it won't append the ID on the end, meaning scaling the service causes a naming conflict:
```
Conflict. The container name "/ansibleplugintestingconjurhostidentity-test_app_ubuntu" is already in use by container "<container_id>". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by john-odonnell** [comment]
I was going to note that we should also extend this fix to the tests in `roles/conjur_host_identity/tests/`, but I don't think we can apply this same strategy.

The tests there have the same problem when building Ansible's inventory with `inventory.j2` - the separators around `test_app_x` change with docker-compose version:
```
testapp]
{{ lookup('env','COMPOSE_PROJECT_NAME') }}_test_app_ubuntu_[1:2] ansible_connection=docker
{{ lookup('env','COMPOSE_PROJECT_NAME') }}_test_app_centos_[1:2] ansible_connection=docker
```

Problem is, if we use `container_name` in the compose file, it won't append the ID on the end, meaning scaling the service causes a naming conflict:
```
Conflict. The container name "/ansibleplugintestingconjurhostidentity-test_app_ubuntu" is already in use by container "<container_id>". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by szh** [comment]
@john-odonnell, yeah, container_name [isn't supported](https://github.com/docker/compose/issues/3722) when using scaling, so we'll need another strategy for these tests. Is it worthwhile to add some code [here](https://github.com/cyberark/ansible-conjur-collection/blob/fix-tests-docker-compose-v2/roles/conjur_host_identity/tests/test.sh#L102) to replace the underscores with hyphens if docker-compose v2 exists?

**Review by john-odonnell — APPROVED** [review]
LGTM! 👍

**Pull request merged**
