### PR TITLE
Encode spaces correctly

### PR DESCRIPTION
**Pull request by orenbm**
Connected to ansible/awx#7191
Blocked by #7 

Previously we used `urllib.parse`'s `quote_plus` function
to encode strings. However, this method replaces spaces with
`+` instead of `%20` which resulted in a 404 Not Found error
as in the server side we interpret `%20` as a space and leave
the `+` as it is.

More info can be found in the definition of `quote_plus`: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus

### CODE REVIEW

**Comment by orenbm** [comment]
hey @cyberark-bizdev :)

Do we have any tests for this repo? How do you verify the quality of PR changes?

would be great to add a test with a variable that has spaces in it.

**Comment by izgeri** [comment]
@orenbm it seems important to have a changelog entry for this - can you please add one?

**Comment by orenbm** [comment]
> @orenbm it seems important to have a changelog entry for this - can you please add one?

thanks for the reminder @izgeri :)

**Comment by orenbm** [comment]
@cyberark-bizdev thanks for the review. Please do not merge PRs that are not green as the build is now broken. I think that it is always best to just approve the PR without merging because the PR creator might have other plans in mind. I didn't want to merge this PR immediately as we had another PR that added tests to our pipeline and i wanted to add a test to this one. The changelog was also needed to be updated in this PR to match the standards.

**Comment by orenbm** [comment]
Also - please don't merge the `master` branch into a side branch to update it (i am guessing you pushed the "Update branch" button in the UI). It creates a weird git history. If a branch needs to be update we use "fetch + rebase".

**Comment by mkkeffeler** [comment]
has the version that this plugin fix is included in been included in any ansible release's to date? we are running ansible 2.9.9 and still seeing this fail

**Comment by sgnn7** [comment]
Hey @mkkeffeler, this fix is in v1.0.5+ Ansible Galaxy plugin found here: https://galaxy.ansible.com/cyberark/conjur. Given your comments in [this](https://github.com/cyberark/ansible-conjur-collection/issues/29) issue though, you are using AWX and your AWX plugin is not the same codebase so this fix may not apply to you even if it's published.

**Comment by mkkeffeler** [comment]
well just to be clear, the issue reported there doesn’t use the AWX plugin, the credential retrieval is happening inside the ansible playbook itself, if that makes a difference.

And how can I track down then whether my version of ansible is using that version or greater of the plugin?

**Comment by sgnn7** [comment]
@mkkeffeler I'll answer that in the [original issue](https://github.com/cyberark/ansible-conjur-collection/issues/29) so that we don't pollute this unrelated one.

**Pull request merged**
